paths: 
    /pingui:
    get:
      description: Endpoint for Healthcheck, but more fancy...
      responses:
        200:
          description: Returns a pongo fancy response.
  /ping:
    get:
      description: Endpoint for Healthcheck
      responses:
        200:
          description: Returns pong.
  /api/items:
      method:
        tags: [items, shopping]
        summary: "GET"
        produces: [application/json]
        parameters:
          - name: "q"
            description: "Keyword to search in the api"
            in: query
            required: true
            type: string
            example: "cubo rubik"
        responses:
          200:
            description: "Devuelve una lista de objetos"
            schema:
              type: object
              properties:
                author:
                  description: "Who did this api"
                  type: object
                  example: false
                categories:
                  description: "Categories trees related from those items"
                  type: array
                    items:
                      type: string
                  example: true
                items:
                  description: "Items retrieved"
                  type: boolean
                  example: false
          502:
            description: "Service goes trough 502 error when the resource was not founded from the external api."
            schema:
              type: object
              properties:
                error:
                  description: "Error description"
                  type: string
                  example: "Bad gateway"
                code: 
                  description: "HTTP Error code"
                  type: number
                  example: 502