---
apis:
  - "./routes/*.js"
definition:
  openapi: 3.0.0
  info:
    title: awesome-marketplace-api
    version: 0.1.0
    description: Esta api alimenta de datos a la aplicación web del marketplace
    license:
      name: MIT
      url: https://spdx.org/licenses/MIT.html
    contact:
      name: Facundo Palombo
      url: https://github.com/FacundoPalombo
      email: facundo.palombo@gmail.com
  servers:
    - url: http://localhost:3001/
      description: Local server
  paths:
  components:
    schemas:
      Price:
        type: object
        properties:
          currency:
            type: string
          amount:
            type: number
          decimals:
            type: number
      Author:
        type: object
        properties:
          name:
            type: string
          lastname:
            type: string
        example:
          name: Jhon
          lastname: Doe
      Item:
        type: object
        description: Item from a list of products
        properties:
          item:
            properties:
              id:
                type: string
              title:
                type: string
              price:
                $ref: "#/components/schemas/Price"
              picture:
                type: string
              condition:
                type: string
              free_shipping:
                type: boolean
              sold_quantity:
                type: number
              description:
                type: string
      Items:
        type: object
        description: Items listed with categories
        properties:
          categories:
            type: array
            items:
              type: string
          items:
            type: array
            items:
              $ref: "#/components/schemas/Item"
      ItemsResponse:
        type: object
        description: Items listed with categories, response from service
        $ref: "#/components/schemas/Items"
        additionalProperties: true
        properties:
          author:
            $ref: "#/components/schemas/Author"
      ItemResponse:
        type: object
        description: Item response from service
        $ref: "#/components/schemas/Item"
        additionalProperties: true
        properties:
          author:
            $ref: "#/components/schemas/Author"
      HttpError:
        description: "HTTP Error code"
        schema: 
          type: object
          properties:
            message:
              type: string
              description: 'Error message'
              example: "Not Found"
            code:
              type: integer
              description: "HTTP Status code"
              example: 404